{
 "title": "mainnet",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "replay_behind", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Snapshot Load Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "replay_snapshot_status_snapshot_begin",
     "legendFormat": "__auto"
    },
    {
     "expr": "replay_snapshot_status_snapshot_end != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "replay_snapshot_status_incremental_begin != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "replay_snapshot_status_incremental_end != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replay Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "replay_slot != 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Caught Up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "replay_caught_up", "legendFormat": "__auto" }
   ]
  }
 ]
}