[gossip]
    port = 9967
[tiles]
    [tiles.gossip]
        entrypoints = ["51.195.234.217"]
        peer_ports = [8001]
        gossip_listen_port = 9967
    [tiles.repair]
        repair_intake_listen_port = 8693
        repair_serve_listen_port = 8410
    [tiles.replay]
        snapshot = "wksp:/data/chali/mainnet-funk"
        incremental = "/data/chali/incremental-snapshot-268539268-268547021-HhHx3mss6NTXm2tZxvddi4xYNWUKEWYCddQsgVs85dkE.tar.zst"
        tpool_thread_count = 13
        funk_sz_gb = 600
        funk_txn_max = 1024
        funk_rec_max = 600000000
[consensus]
    expected_shred_version = 50093
[log]
  path = "fddev.log"
  level_stderr = "NOTICE"
[development]
    topology = "firedancer"

