[gossip]
    port = 9406
[tiles]
    [tiles.gossip]
        entrypoints = ["147.75.84.157"]
        peer_ports = [8000]
        gossip_listen_port = 9406
    [tiles.repair]
        repair_intake_listen_port = 8633
        repair_serve_listen_port = 9874
    [tiles.replay]
        snapshot = "wksp:/data/chali/mainnet-funk"
        incremental = "/data/chali/incremental-snapshot-268513121-268538757-CytUvAc3XbCDL8gm7qTZEnKTxuMH2LsLKvMjsN5AnNMS.tar.zst"
        tpool_thread_count = 13
        funk_sz_gb = 600
        funk_txn_max = 1024
        funk_rec_max = 600000000
[consensus]
    expected_shred_version = 50093
[log]
  path = "fddev.log"
  level_stderr = "NOTICE"
[development]
    topology = "firedancer"

